"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emptyBoard = exports.LINE_LENGTH = exports.specialChar = exports.characterCodeArray = exports.characterCode = void 0;
exports.characterCode = {
    ' ': 0,
    a: 1,
    b: 2,
    c: 3,
    d: 4,
    e: 5,
    f: 6,
    g: 7,
    h: 8,
    i: 9,
    j: 10,
    k: 11,
    l: 12,
    m: 13,
    n: 14,
    o: 15,
    p: 16,
    q: 17,
    r: 18,
    s: 19,
    t: 20,
    u: 21,
    v: 22,
    w: 23,
    x: 24,
    y: 25,
    z: 26,
    A: 1,
    B: 2,
    C: 3,
    D: 4,
    E: 5,
    F: 6,
    G: 7,
    H: 8,
    I: 9,
    J: 10,
    K: 11,
    L: 12,
    M: 13,
    N: 14,
    O: 15,
    P: 16,
    Q: 17,
    R: 18,
    S: 19,
    T: 20,
    U: 21,
    V: 22,
    W: 23,
    X: 24,
    Y: 25,
    Z: 26,
    1: 27,
    2: 28,
    3: 29,
    4: 30,
    5: 31,
    6: 32,
    7: 33,
    8: 34,
    9: 35,
    0: 36,
    '!': 37,
    '@': 38,
    '#': 39,
    $: 40,
    '(': 41,
    ')': 42,
    '-': 44,
    '+': 46,
    '&': 47,
    '=': 48,
    ';': 49,
    ':': 50,
    "'": 52,
    '"': 53,
    '%': 54,
    ',': 55,
    '.': 56,
    '/': 59,
    '?': 60,
    '°': 62,
    degreeSign: 62,
    redBlock: 63,
    orangeBlock: 64,
    yellowBlock: 65,
    greenBlock: 66,
    blueBlock: 67,
    violetBlock: 68,
    whiteBlock: 69,
    blackBlock: 70,
    filled: 71,
    '*degreeSign': 62,
    '*redBlock': 63,
    '*orangeBlock': 64,
    '*yellowBlock': 65,
    '*greenBlock': 66,
    '*blueBlock': 67,
    '*violetBlock': 68,
    '*whiteBlock': 69,
    '*blackBlock': 70,
};
exports.characterCodeArray = Object.entries(exports.characterCode).reduce((acc, [key, value]) => {
    if (acc.indexOf(key) === -1) {
        acc[value] = key;
    }
    return acc;
}, []);
exports.specialChar = [
    'degreeSign',
    'redBlock',
    'orangeBlock',
    'yellowBlock',
    'greenBlock',
    'blueBlock',
    'violetBlock',
    'whiteBlock',
    'blackBlock',
    '*degreeSign',
    '*redBlock',
    '*orangeBlock',
    '*yellowBlock',
    '*greenBlock',
    '*blueBlock',
    '*violetBlock',
    '*whiteBlock',
    '*blackBlock',
    '*return',
    '',
];
exports.LINE_LENGTH = 22;
const emptyLine = new Array(exports.LINE_LENGTH).fill(0);
exports.emptyBoard = new Array(6).fill(emptyLine);
